---
# tasks file for sample-apache
- name: install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - httpd
    - mod_ssl
    - php

- name: set firewall config
  block:
    - firewalld:
        service: http
        state: enabled
  rescue:
    - debug: msg="error"

- name: copy template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify:
    restart_web
