---
- name: Display running playbook
  debug:
    msg: "galera_cluster_join.yml"

- name: Check if cluster has already been bootstraped
  stat:
    path: /etc/my.cnf.d/bootstrap_ok
  register: bootstrap_state

- name: Fail if cluster is already bootstraped
  fail: msg="The flag file {{ bootstrap_state }} exists. The cluster has already been bootstraped"
  when: bootstrap_state.stat.exists

- name: MySQL configuration file
  template:
    src: ../templates/galera_cluster.cnf.j2
    dest: /etc/my.cnf.d/galera_cluster.cnf
    owner: root
    group: root
    mode: 0644
    
- name: Start MySQL/MariaDB
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create the flag file
  file:
    path: /etc/my.cnf.d/bootstrap_ok
    state: touch

