 - hosts: all
   remote_user: ansiblemgnt
   become: yes

   tasks:
    - name: Copy color_ps1_test.sh to /etc/profile.d
      copy:
        src: "../files/color_ps1_test.sh"
        dest: /etc/profile.d/color_ps1.sh
        owner: root
        group: root
        mode: 0644
