---
- { include_vars: "postgres_{{ env}}.yml" } # Load correct variables for env

- { include: manage.yml, become: true } 
- { include: backup.yml, become: true }
- { include: monitoring.yml, become: true } 
- { include: logrotate.yml, become: true } 
