---
- name: Display running playbook
  debug:
    msg: "create_patroni_service.yml"

- name: patroni service file
  template:
    src: "{{ role_path }}/templates/patroni.service.j2"
    dest: "/etc/systemd/system/patroni.service"
    owner: root
    group: root
    mode: 0755

- name: systemd to reread configs
  systemd:
    daemon_reload: yes

- name: Enable the systemd patroni service
  systemd:
    name: patroni
    enabled: yes

- name: Start the systemd patroni service
  systemd:
    name: patroni
    state: started